version: "3.9"

services:
  # Use sequelite for dev
  # db:
  #   image: postgres:latest
  #   container_name: sparepal_db_dev
  #   restart: always
  #   ports:
  #     - "5444:5432"
  #   environment:
  #     # Create postgres db super user with password
  #     - POSTGRES_USER=${DB_USERNAME}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #     - POSTGRES_DB=${DB_NAME}
  #   # env_file: .env
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  #     # Create project db user, project db and give privileges to the user on the db
  #     - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U $${DB_USERNAME}"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  redis:
    image: redis:latest
    container_name: redis_dev
    restart: always

  web:
    container_name: web_dev
    build: .
    ports:
      - 8000:8000
    # env_file:
    #   - ./.env
    volumes:
      - web-data:/app
    depends_on:
      # - db
      - redis
    command: python manage.py runserver 0.0.0.0:8000
      
  celery:
    container_name: celery_dev
    build: .
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      # - db
      - redis
      - web
    command: celery -A core worker -l info

volumes:
  # db-data:
  web-data: