# Generated by Django 5.1.1 on 2024-10-15 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('date_registered', models.DateField()),
                ('tin_number', models.CharField(max_length=20)),
                ('renewed_license_date', models.DateField()),
                ('license_number', models.CharField(max_length=100)),
                ('legal_status', models.CharField(choices=[('Sole Proprietorship', 'Sole Proprietorship'), ('Partnership', 'Partnership'), ('Limited Liability Supplier', 'Limited Liability Supplier'), ('Corporation', 'Corporation')], max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('business_description', models.CharField(choices=[('Retailer', 'Retailer'), ('Wholesaler', 'Wholesaler'), ('Distributor', 'Distributor'), ('Manufacturer', 'Manufacturer')], max_length=100)),
                ('sub_group_code', models.CharField(max_length=50)),
                ('sub_group_description', models.CharField(choices=[('Automotive Parts', 'Automotive Parts'), ('Electronics', 'Electronics'), ('Machinery', 'Machinery'), ('Tools', 'Tools')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyManagerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_full_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('manager_phone_number', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='suppliers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Addis Ababa', 'Addis Ababa'), ('Oromia', 'Oromia'), ('Amhara', 'Amhara'), ('Tigray', 'Tigray')], max_length=100)),
                ('zone', models.CharField(choices=[('Central', 'Central'), ('East', 'East'), ('West', 'West')], max_length=100)),
                ('woreda', models.CharField(choices=[('Woreda 1', 'Woreda 1'), ('Woreda 2', 'Woreda 2'), ('Woreda 3', 'Woreda 3')], max_length=100)),
                ('kebele', models.CharField(choices=[('Kebele 1', 'Kebele 1'), ('Kebele 2', 'Kebele 2'), ('Kebele 3', 'Kebele 3')], max_length=100)),
                ('house_number', models.CharField(max_length=50)),
                ('business_phone_number', models.CharField(max_length=20)),
                ('capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('site_id', models.CharField(choices=[('Site A', 'Site A'), ('Site B', 'Site B'), ('Site C', 'Site C')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='suppliers.supplier')),
            ],
        ),
    ]
